name: 'testing workflow'
# Trigger on push
on: 
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
  release:
    types: 
      - published
jobs:
  test:
    name: somethingDope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
            twitter_status: '💥 𝕋𝕙𝕖𝕣𝕖 𝕚𝕤 𝕒 𝕟𝕖𝕨 𝕔𝕠𝕞𝕞𝕚𝕥 𝕚𝕟 𝕞𝕒𝕤𝕥𝕖𝕣 𝕓𝕣𝕒𝕟𝕔𝕙! 💥 ${{ github.event.commits[0].message }}'
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
