name: 'testing workflow'
# Trigger on push
on: push
  
jobs:
  test:
    name: somethingDope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
            twitter_consumer_key: test1 #${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: test2 #${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: test3 #${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: test4 #${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
